language: python
cache: pip
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
 - "pypy"
 - "pypy3"

matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true

notifications:
  email: false
before_install:
 - export GOPATH=~/go
 - go get github.com/BurntSushi/toml-test
install:
 - pip install tox-travis
 - python setup.py install
script:
 - ~/go/bin/toml-test ./tests/decoding_test.sh
 - tox
 - tox -e check
after_success:
 - tox -e codecov
